# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{objected_conditions}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damien MATHIEU"]
  s.date = %q{2010-12-14}
  s.description = %q{Object Oriented Conditions}
  s.email = %q{42@dmathieu.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".bundle/config",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "lib/objected_conditions.rb",
    "lib/objected_conditions/base.rb",
    "lib/objected_conditions/common.rb",
    "lib/objected_conditions/else_object.rb",
    "lib/objected_conditions/if_object.rb",
    "lib/objected_conditions/unless_object.rb",
    "spec/objected_conditions/base_spec.rb",
    "spec/objected_conditions/common_spec.rb",
    "spec/objected_conditions/else_object_spec.rb",
    "spec/objected_conditions/if_object_spec.rb",
    "spec/objected_conditions/unless_object_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dmathieu/objected_conditions}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Object Oriented Conditions}
  s.test_files = [
    "spec/objected_conditions/base_spec.rb",
    "spec/objected_conditions/common_spec.rb",
    "spec/objected_conditions/else_object_spec.rb",
    "spec/objected_conditions/if_object_spec.rb",
    "spec/objected_conditions/unless_object_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
      s.add_runtime_dependency(%q<sdoc>, [">= 0"])
      s.add_runtime_dependency(%q<sdoc-helpers>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
      s.add_dependency(%q<sdoc>, [">= 0"])
      s.add_dependency(%q<sdoc-helpers>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
    s.add_dependency(%q<sdoc>, [">= 0"])
    s.add_dependency(%q<sdoc-helpers>, [">= 0"])
  end
end

